### ISSUE TITLE
Sync S3-Compatible Object Storage 

### ISSUE THREAD

**Issue by akashcse** [EMCECS/ecs-sync#102]
I have S3-Compatible Object Storage  provided by DataCore Swarm. Its working fine with S3 browser.
But when i try to sync using this library got exception like "
com.emc.ecs.sync.config.ConfigurationException: cannot determine if Source bucket exists"
I investigate further more 
in S3 browser its connect to REST Endpoint like : rest-url/{bucket-name}
in this lib its try to connect REST Endpoint like : {bucket-name}.rest-url and its not working 
Note : S3-Compatible Object Storage does not have any region

**Comment by xiaoxin-ren** [comment]
Please try disable vHosts ("Specifies whether virtual hosted buckets will be disabled (and path-style buckets will be used)").
