### ISSUE TITLE
Sync only new/updated files from Source to Target

### ISSUE THREAD

**Issue by akashcse** [EMCECS/ecs-sync#103]
Is there any way to sync only new/updated file from source to target?
As target already contains source files. 
I want to sync only required files as my target already had all source files.

**Comment by xiaoxin-ren** [comment]
You can make it by retrying the same sync task. The objects from source won't be copied to target again if it's not modified/updated.

**Comment by hoelgu** [comment]
Make sure to choose a db name to orevent the deletion should you archive the job

Holger Jakob
+41 79 415 56 22

On 30 Aug 2023, at 20:58, Eric Ren ***@***.***> wrote:

﻿

You can make it by retrying the same sync task. The objects from source won't be copied to target again if it's not modified/updated.
