### ISSUE TITLE
Is there any way to copy files from source to target skipping the source folder sync only files?

### ISSUE THREAD

**Issue by akashcse** [EMCECS/ecs-sync#105]

**Comment by xiaoxin-ren** [comment]
Assuming the ask is to sync to ECS S3 target, you can leverage `<preserveDirectories>false</preserveDirectories>`.  Please refer to the description for this option "By default, directories are stored in S3 as empty objects to preserve empty dirs and metadata from the source. Turn this off to avoid copying directories. Note that if this is turned off, verification may fail for all directory objects"

**Comment by akashcse** [comment]
@xiaoxin-ren 
My scenario  sync ECS S3 to ECS S3.
<preserveDirectories>false</preserveDirectories> need to add on source or target configuration ?

**Comment by xiaoxin-ren** [comment]
It's for target.
