### ISSUE TITLE
S3 to ECS migration error

### ISSUE THREAD

**Issue by vieirb1** [EMCECS/ecs-sync#107]
Hi!

       When doing a copying from a S3 storage to ECS using ECSSync, the objects are copied, to target, but reports the following error:
       
       "","[com.sun.jersey.api.client.ClientHandlerException: com.amazonaws.SdkClientException: Unable to verify integrity of data download.  Client calculated content hash didn't match hash calculated by Amazon S3.  The data may be corrupt.] "

      Any ideais?!

     Thanks in advance!

**Comment by xiaoxin-ren** [comment]
Is there a full backtrace from /var/log/ecs-sync/ecs-sync.log ?  You can re-run the sync task so that the failures will be retried.

**Comment by dunedodo** [comment]
As it has been a long time since the last response, I'll close the ticket. Please feel free to reopen it if you hit the same issue.
