### ISSUE TITLE
FAQ question

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ecs-sync#12]
Hi all
If I re-run a CAS to CAS job, will the query start back at epoch to now or is there a saved timestamp which will result in a query of timestamp to now?
Thanks, Holger

**Comment by twincitiesguy** [comment]
It will start over.  However, if you reuse the same database table to track the sync, it will skip over all of the clips that were already transferred.  When using the UI, simply set a DB table name and reuse the same name in iterative syncs.

Note that it may take a while to catch up to where it was before if the migration includes millions of objects, but it is obviously much faster than remigrating everything.

**Comment by holgerjakob** [comment]
Hi
Thanks a lot. A query in a large system may take ages, That's why I thought maybe the latest query point is saved. 
It would help in a cas source to be able to specify starting and endpoint of the query. This would then just add new clips to the database and migrate only the new ones without having to worry about an instable query.
CU, Holger
