### ISSUE TITLE
Centera SDK Installation question

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ecs-sync#13]
Hi all

I'm trying to use ecs-sync in a custom vm instead of the OVA. I followed the installation steps of the wiki in a minimal centos 7 installation.

copy ecs-sync-3.1.1.zip to /usr/local
yum install unzip
cd /usr/local
unzip ecs-sync-3.1.1.zip
copy ecs-sync-ui-3.1.1.jar to /usr/local/ecs-sync-3.1.1
delete ecs-sync-3.1.1.zip in /usr/local
sudo yum update
cd ecs-sync-3.1.1
ova/configure-centos.sh
set mariadb password
remove anonymous user
disallow root from remote
remove test database
reload privilege tables
ova/install.sh

In oder to install the Centera SDK Version 3.4 I did the following as root:
copy Centera_SDK_Linux-gcc4.tgz to /usr/tmp
cd /usr/tmp
gzip -d Centera_SDK_Linux-gcc4.tgz
tar -xvf Centera_SDK_Linux-gcc4.tar
./install

echo "PATH=${PATH}:/usr/local/Centera_SDK/lib/64" > /etc/profile.d/CenteraSDK-path.sh && chmod 755 /etc/profile.d/CenteraSDK-path.sh
echo "LD_LIBRARY_PATH=/usr/local/Centera_SDK/lib/64" > /etc/profile.d/CenteraLIB-path.sh && chmod 755 /etc/profile.d/CenteraLIB-path.sh

. /etc/profile

Logged on to the GUI and created a CAS to CAS Migration job.
[java.lang.UnsatisfiedLinkError: com.filepool.natives.FPLibraryNative.setLastError(I)V] java.lang.UnsatisfiedLinkError: com.filepool.natives.FPLibraryNative.setLastError(I)V at com.filepool.natives.FPLibraryNative.setLastError(Native Method) at com.filepool.fplibrary.FPLibraryException.retrieveErrorString(Unknown Source) at com.filepool.fplibrary.FPLibraryException.<init>(Unknown Source) at com.filepool.fplibrary.FPPool.RegisterApplication(Unknown Source) at com.emc.ecs.sync.storage.cas.CasStorage.configure(CasStorage.java:96) at com.emc.ecs.sync.EcsSync.run(EcsSync.java:213) at com.emc.ecs.sync.service.SyncJobService$SyncTask.run(SyncJobService.java:310) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

The Centera SDK Installation documentation only states:
Go to the Centera_SDK/install subdirectory on your machine and run the install
script. Run the script with root privileges since it installs files in system directories.
You may want to modify this script to reflect your own directory structure. Add the
directory where the libraries were installed to the library path environment variable
(LD_LIBRARY_PATH).

Where do the path and ld_library_path variables need to be configured so that the ecs-sync processes see them correctly?
Do I just need to restart something?
Do I need to set the path to the 32bit version?
Do I need the 3.3 Version instead of 3.4?
The other GCC Version?

As it's working in the OVA image, you probably know where I went the wrong way :-)
I'm testing for a migration of several hundred millions of clips.

Thanks, Holger

**Comment by twincitiesguy** [comment]
Looks like you need to export those variables in your /etc/profile.d scripts.  Simply put "export " in front of the existing lines.

**Comment by holgerjakob** [comment]
Hi Stu
That worked out fine. It required a reboot of the machine afterwards for the ecs-sync processes to see these exports. Maybe there is a simpler way but that worked for me.

As a reference for others that want to install on their own:
echo "export PATH=${PATH}:/usr/local/Centera_SDK/lib/64" > /etc/profile.d/CenteraSDK-path.sh && chmod 755 /etc/profile.d/CenteraSDK-path.sh
echo "export LD_LIBRARY_PATH=/usr/local/Centera_SDK/lib/64" > /etc/profile.d/CenteraLIB-path.sh && chmod 755 /etc/profile.d/CenteraLIB-path.sh
reboot


Thanks a lot, Holger
