### ISSUE TITLE
ECS Metering Output with 0 capacity after Centera CAS to ECS CAS Migration

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ecs-sync#14]
Hi all

I migrated a couple of pools from Center CAS to ECS CAS using ecs-sync. After the migration, the metering output in ECS shows the objects, but the capacity remains at 0. 
Is this an ECS issue (already know?) or something that concerns ecs-sync?
As the ECS Migration Tool does not geo-replicate migrated content it is basically useless and ecs-sync or other tools need to be used. But if capacity shows 0 after the migration, one or the other customer may be concerned about his data.

Thanks, Holger

**Comment by twincitiesguy** [comment]
Depending on what version of ecs-sync you're using, all of the migration details should be in the database.  If you want to know how many total bytes of user data were transferred, you can run the following query against the DB table:

`select sum(size) from <table_name> where status = 'Verified';`
(if you did not enable verification, then the status will be `'Transferred'`)

You can also see a breakdown of how many objects completed successfully and how many failed with the following query:

`select status, count(*) from <table_name> group by status;`

Given that ECS has a metering delay of between a few minutes and a couple hours (depending on the version), it's possible the usage simply wasn't available yet.  If you think the amount reported is wrong, feel free to open an SR and have support take a look.
