### ISSUE TITLE
Read the Docs site

### ISSUE THREAD

**Issue by ksteinfeldt** [EMCECS/ecs-sync#15]

**Comment by robabrams** [comment]
Please can you email the root password for the 3.2.7 OVA image ?
rob.abrams@stg.co.za

**Comment by Mikeguy74** [comment]
Does anyone have any of the credentials for the 3.2.7 OVA?  I have deployed it and have tried the admin and ecs-sync combination but I keep getting an error that says Log in incorrect.  I have tried rebooting and still not able to get logged in.  Any help would be greatly appreciated.  My email is in my readme file in my profile.

**Comment by xiaoxin-ren** [comment]
Hi @Mikeguy74, sorry that OVA installation is no longer updated, and it's recommended to run the installation scripts on a CentOS 7 image. You can find latest release v3.4.2 from [https://github.com/EMCECS/ecs-sync/releases](url),  see instructions from [https://github.com/EMCECS/ecs-sync/wiki/Service-Installation](url).

**Comment by Mikeguy74** [comment]
Hi @xiaoxin-ren Is it possible to run ECS-Sync from RHEL 7 instead?  We use RHEL, but I do not have CentOS inhouse.  I would imagine from the service installation page that RHEL is acceptable as well, correct?

**Comment by xiaoxin-ren** [comment]
@Mikeguy74, yes, RHEL 6.4+ is supported.

**Comment by Mikeguy74** [comment]
Thank you very much!

Thank you,
Mike Severson
Enterprise Backup/Archive Administrator | Information Technology
BLUE CROSS BLUE SHIELD OF NORTH DAKOTA, FARGO
(701)277-2145 (work)
Mike.Severson@BCBSND.com<mailto:Mike.Severson@BCBSND.com>
Core hours: 8 AM – 4:30 PM CST

Vacation Alerts:
Aug 5-8

TRAINING DATES:
July 27-28
August 12-13

[BCBSND logo]

Confidentiality Notice: This communication and any attachments are for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure, distribution or copying is prohibited. If you are not the intended recipient(s), please contact the sender by replying to this e-mail and destroy/delete all copies of this e-mail message.

**Comment by twincitiesguy** [comment]
Closing as it looks like we will continue using the wiki for the foreseeable future
