### ISSUE TITLE
Getting XML out of ecs-sync-ui

### ISSUE THREAD

**Issue by cmarzullo** [EMCECS/ecs-sync#17]
When I construct an XML nothing seems to get transferred I see the following in the logs:
```
Aug 14 15:14:03 ecssync java[9553]: 2017-08-14 15:14:03 INFO  [sync-pool-41-t-1] SyncTask: O--* skipping /vol1/pathogen/sample1920X1080dpx10bit.dpx because it is up-to-date in the target
Aug 14 15:14:03 ecssync java[9553]: 2017-08-14 15:14:03 INFO  [sync-pool-41-t-2] SyncTask: O--* skipping /vol1/pathogen/delete_test.png because it is up-to-date in the target
```

But there's nothing in the bucket!

I feel I'm doing my XML with the wrong settings. Is there a away to get the XML from the job submitted via the UI? So I can verify I'm using the right values?

**Comment by twincitiesguy** [comment]
To verify your settings, you can change the log level of the service to "Verbose".  This can be done via the UI or the -ctl command (`ecs-sync-ctl --set-log-level verbose`).  When you start a job, it will print all of the parsed settings in the log.

I would guess that you are using the same database table that you used in a previous job.  You should use a different database table for each source/target data set.  If you are submitting via the UI, you can also just leave the database table blank and it will auto-generate a unique table.  Just be aware that auto-generated tables are deleted when their jobs are archived.

**Comment by cmarzullo** [comment]
setting the server to verbose mode let me get the configuration options and see the raw options.

Comparing the UI output from when I submitted XML I see the UI didn't set the dbTable value, it was NULL. In my XML I was setting it to `files_to_ecs` I'm not sure why I had that set.

Seems to be working at the moment. Thanks for the prompt response.
