### ISSUE TITLE
Access request

### ISSUE THREAD

**Issue by spodiedog** [EMCECS/ecs-sync#22]
The URL https://share.object.ecstestdrive.com/bucket-perf-3.1.jar?AWSAccessKeyId=130753149435015067@ecstestdrive.emc.com&Expires=1503707596&Signature=77oqhE2C4m7Q4mtV5WE8%2BujD4q0%3D generates the error message that access is denied.

Please identify the process by which I may gain access.

**Comment by twincitiesguy** [comment]
Link corrected to latest version in [Service Installation](https://github.com/EMCECS/ecs-sync/wiki/Service-Installation) page.
