### ISSUE TITLE
--store-metadata doesn't work

### ISSUE THREAD

**Issue by jmayday** [EMCECS/ecs-sync#24]
By some reason I can't force storing metadata when cloning atmos space to filesystem. 

```
Unrecognized option: --store-metadata
    use --help for a detailed (quite long) list of options
```

The way I run ecs-sync is as following:
```
C:\ecs-sync\build\libs>java -jar ecs-sync-3.2.5.jar -source atmos:http:/tokenId@host:port -target file:c:\atms\ecslocal --log-level verbose --store-metadata
```

Seems like --store-metadata option is not consumed as after modifying source code and recompiling (changing boolean assignment storeMetadata = true in config class) I was able to get metadata persisted on file system.

**Comment by jmayday** [comment]
Well, I'm blind. I didn't notice the prefix requirement for this option.

**Comment by jmayday** [comment]
Can't get the --store-metadata working. 

```
 NOTE: Storage options must be prefixed by source- or target-, depending on
    which role they assume
```

```
--store-metadata                              when used as a target, stores
                                                  source metadata in a json
                                                  file, since filesystems have
                                                  no concept of user metadata
```

How to use this option?

**Comment by twincitiesguy** [comment]
@jmayday, the option has no value.  To use it, simply put `--target-store-metadata` by itself as an option (do not add `=true`).  Also, always be sure to specify the `--source`, `--filters`, and `--target` options first.
