### ISSUE TITLE
QUESTION: does CAS - CAS copy all ARM information

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ecs-sync#26]
Hi all
This is more of a question that has come up recently. Does an ECS-Sync CAS to CAS migration copy all of the ARM information to ECS? Events, Holds to be precise.

Thanks, Holger

**Comment by twincitiesguy** [comment]
The short answer is no, it does not.  However, EMC professional services does have an internal version of the CAS SDK with this capability and so they have the ability to perform such migrations using ecs-sync.  Unfortunately, given the sensitivity of the CAS SDK and the particulars of this special release, we cannot make it public.
