### ISSUE TITLE
3.2.7 ova deployment: running nmtui impossible

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ecs-sync#27]
Hi all
I deployed the most recent ova today and tried somehow to log in to the console. The old root user password somehow did not work. Was that changed?
Or are we supposed to use a admin user at the linux level?

The wiki states to change the os passwords but does not list them. I remember they were once there.

Other than that on 3.2.6 we ran 100 threads which migrated more than 700 clips per second, small files, from Centera to a virtual ECS CE. Customer was impressed about the performance.

Thanks a lot, Holger

**Comment by twincitiesguy** [comment]
On the OVA, the ecssync user is an admin, so there is no need for the root password.  Moving forward, the root user can no longer be used to login.

The ecssync password should be in your professional services documentation, or you can email the migration team DL.
