### ISSUE TITLE
No documentation on configuring access to an SMTP server for Alerts

### ISSUE THREAD

**Issue by jrosenth** [EMCECS/ecs-sync#29]
There is no documentation or information on how or where to configure the SMTP server and account for sending alerts.

The GUI forces you to enter and email address to send alerts to, but that's it :-(

FYI - The SMTP config is actually in /opt/emc/ecs-sync/application-production.yml.  There are some commented lines you can uncomment if necessary.

**Comment by twincitiesguy** [comment]
Added note in wiki:
https://github.com/EMCECS/ecs-sync/wiki/Initializing-the-UI#configure-smtp-server-for-alerts
