### ISSUE TITLE
Verbose log level leaks sensitive information

### ISSUE THREAD

**Issue by MarkRx** [EMCECS/ecs-sync#32]
If the generated URI for a source/target has credentials in it they will be printed in the log if verbose logging is on.

Line in question: https://github.com/EMCECS/ecs-sync/blob/master/src/main/java/com/emc/ecs/sync/EcsSync.java#L293

The sensitive information should be masked.

**Comment by twincitiesguy** [comment]
Sensitive info scrubbing in the logs was added to 3.5.0.  If we missed something, please let us know.
