### ISSUE TITLE
ECS sync not recognizing the include-version options

### ISSUE THREAD

**Issue by rpulikool** [EMCECS/ecs-sync#37]
Hi,

I am trying to copy bucket to bucket copy with option to include version and it doesn't seems to take that options stating unrecognized options.

Any help will be appreciated

Regards,

**Comment by twincitiesguy** [comment]
It would help if you could provide the method of execution (XML, UI, etc.), the configuration details (scrub any sensitive info), and the error log with a full stack trace.

**Comment by rpulikool** [comment]
I have that figured out..Thanks anyways
