### ISSUE TITLE
When a job is launched with a XML file, display its file name in GUI and ecs-sync-ctl --status

### ISSUE THREAD

**Issue by lriva94** [EMCECS/ecs-sync#39]
Hello,
this is an enhancement request:

ability to display the name of the config XML file when a job is launched with such a file like:

ecs-sync-ctl --submit <XML_file>

This file name should be displayed in the GUI when clicking on a job  in the status display, and when running ecs-sync-ctl --status <jobid>

Thnaks

**Comment by twincitiesguy** [comment]
Sync jobs can have names now.  By default, when submitting an XML job via the `ecs-sync-ctl` command, the name of the job will be the XML file name.
