### ISSUE TITLE
DX Extraction Filter (dx-extractor) and CIFS-ECS Ingest Filter (cifs-ecs-ingester)

### ISSUE THREAD

**Issue by bhavenjp** [EMCECS/ecs-sync#40]
Hello,

Could you please share an example of how to use dx-extractor and cifs-ecs-ingester filter?
The objective is to migrate DX CAS to CIFS-ECS. Thank you.

**Comment by twincitiesguy** [comment]
These filters rely on some external tools that are no longer available, so unfortunately, they will no longer be supported, and will be removed in a future release.

For DX and CUA migrations, your best bet is to use robocopy (for SMB) or rsync (for NFS), or engage a DellEMC partner to perform the migration.
