### ISSUE TITLE
New Sync Test

### ISSUE THREAD

**Issue by DEO5294** [EMCECS/ecs-sync#45]
I would like to perform a connectivity communication test using the New Sync feature. Can I select Source: Atmos  Target: Simulated Storage for Testing  and fill in the Atmos info with valid information? Will it work? 

![NewSync](https://user-images.githubusercontent.com/48692922/54948756-69d03c80-4f0b-11e9-893e-c4bf248508f9.jpg)

**Comment by twincitiesguy** [comment]
Technically yes, but that will enumerate the entire source namespace, which may take quite a while.

You're better off just starting the migration.  During the configuration process, ecs-sync will verify connectivity to the source and target storage systems.  If that fails, it will not start the migration and you will see a general error message.
