### ISSUE TITLE
CAS Source example

### ISSUE THREAD

**Issue by DEO5294** [EMCECS/ecs-sync#47]
Could someone give me an example of what the CAS "Connection-String" should look like? I am rather confused with:

![UI_connection](https://user-images.githubusercontent.com/48692922/55349928-7828d600-5480-11e9-9317-53f5a21c24f5.jpg)

![SyncUI](https://user-images.githubusercontent.com/48692922/55350154-069d5780-5481-11e9-98f9-570ff96c5159.jpg)

**Comment by twincitiesguy** [comment]
CAS connection details are typically provided in pea files.  When specifying the connection string using a pea file, you simply need a single IP address of the local Centera or ECS cluster and the absolute location of the pea file on disk, like so:
```hpp://10.10.10.1,10.10.10.2?/home/ecssync/my_pool.pea```
In this string, 10.10.10.1 and 10.10.10.2 are the first 2 hosts in the Center cluster.  The pea file is located on the ecs-sync VM at /home/ecssync/my_pool.pea.

More information about the connection string can be found in the CAS SDK documentation, which is distributed with the CAS SDK software package for your application platform.

Note: we highly recommend you use Dell EMC Professional Services when migrating CAS data.

**Comment by DEO5294** [comment]
The piece I was missing was: /home/ecssync/my_pool.pea. I was not exactly sure where to place that pea file at. I have now been successful in moving the files using the ECS Sync UI. Thank you very much. 

As a note: I did contact our DELL EMC Professional Services and was pointed to the WIKI page. 

Thanks again for the quick response. I am very excited to get this rolling now.

**Comment by holgerjakob** [comment]
Hi DEO
We have a steady state of four to six migrations ongoing from Centera to ECS. In case of any questions just drop me an email to holger.jakob@informatio.com
Holger

**Comment by holgerjakob** [comment]
Hi DEO
Somehow my responses to your questions by email got errors back. Holger

**Comment by DEO5294** [comment]
Do you need a different email address to send the examples too? You could change the extension to something that is not common and let me know what it should be. Maybe our email system is kicking them out because of the extension.

David Owings
Blue Cross Blue Shield of North Dakota, Fargo
701-282-1945 (work) | 701-371-7378 (mobile)
dave.owings@bcbsnd.com<mailto:dave.owings@bcbsnd.com>
[BCBSND email signature logo]
Core work hours: Monday-Friday 7:00-3:30 Central Standard Time Zone
