### ISSUE TITLE
Database Tools

### ISSUE THREAD

**Issue by DEO5294** [EMCECS/ecs-sync#50]
Has anyone every used MySQL Workbench to access the ECS-Sync database? If so do you have any tips?

**Comment by twincitiesguy** [comment]
I haven't heard of anyone trying that.  Are you having issues?  Could you include more details?

**Comment by DEO5294** [comment]
I am under the impression that the appliance creates a temporary table/file. I would like to be able use MySQL to see the db info that is collected
