### ISSUE TITLE
ECS-Synch 3.2.7 OVA - DHCP

### ISSUE THREAD

**Issue by seanmulligan2606** [EMCECS/ecs-sync#56]
We are currently using ECS-Synch to migrate data to an ECS S3 Bucket .. UI is working fine, but we need to amend the dhcp network to a static network address, and although we have the instructions to complete this in the OVA, we are unable to find the logon credentials to the VM Console to enable us to do this .. does anybody have any where they can point me to get this information

Thanks

**Comment by lradzki** [comment]
Hello, I need root password too, it would be great if you could email me: lukasz.radzki@symmetry.pl

Thank you in advance!

Lukasz

**Comment by evergreek** [comment]
If I could also receive the root password please - evergreek@gmail.com - thanks!!

**Comment by berislavv** [comment]
Hi
Can you please send the password to berislavv@gmail.com?

We deployed the OVA but it automaticly ask for user/passowrd and the admin/ecs-sync is not working

Thanks

**Comment by cdarko1** [comment]
Hi, can you please send username/password for OVA to daco1980@gmail.com?

Thanks
