### ISSUE TITLE
Empty history-tab in ECS-Sync-UI 3.3.0

### ISSUE THREAD

**Issue by richter71** [EMCECS/ecs-sync#58]
Currently we migrate CAS-Data from Centera to ECS with the ECS-Sync-UI (OVA-Appliance). After a reboot of the ECS-Sync-appliance the history-tab is empty. One can only see the following message: •An error has occurred
Is there a logfile where I can get more information abot that error? How can I restore the history?
Many thanks, Peter

**Comment by richter71** [comment]
additional information: when I click on the history-tab, the following entry is generated in /var/log/ecs-sync/ecs-sync-ui.log:

Illegal character in path at index 51: /download/archive/report/20191016T104521-SPI_WD_Int Incremental 1.report.csv

As you can see, there are blanks in the path.

**Comment by twincitiesguy** [comment]
No, the database table name is not related to the job name at all.  This issue is a known bug (#53).
