### ISSUE TITLE
Two Documentation Suggestions

### ISSUE THREAD

**Issue by amarcionek** [EMCECS/ecs-sync#6]
- Filters are applied in the order specified, right? The doc on the EMC community site doesn't explicitly say that.
- Provide an example of using the Delete Target + Auditing using an ID. It took some looking through the code to really understand what this means.  Here might be an example: importing objects from a file list called `objectlist.txt`, deleting said objects from Atmos source, logging every deleted object to a file `deleted.txt` with the format `[oid], was-deleted`.
  
  `java -jar vipr-sync-1.1.jar --source atmos:http://123456789:xyzabc54321@api.atmosonline.com --source-oid-list objectlist.txt --target delete --deleted-target-id was-deleted --filters id-logging --id-log-file deleted.txt`

**Comment by twincitiesguy** [comment]
@amarcionek, thanks for the suggestions.  We are planning on adding a bit of documentation in the form of wiki pages here for 3.0 and I will take that under advisement.

**Comment by holgerjakob** [comment]
Hi all
It would help to document how the ip address of the ova deployed can be changed or specified when being deployed.
Just migrated from a regular Centera to a cas bucket on ECS virtual. This method allows to use an already existing namespace. The ecs native migration creates a namespace that cannot be renamed afterwards, at least in the community edition.
Worked fine. Holger

**Comment by twincitiesguy** [comment]
@amarcionek, I added a note about filter order in [The Sync UI](url) wiki page and also in the help text.  And there is a [sample XML config](https://github.com/EMCECS/ecs-sync/blob/master/sample/atmos-delete.xml) for deleting from an Atmos subtenant, which can be used as a template for other storage.

@holgerjakob, I added [a section](https://github.com/EMCECS/ecs-sync/wiki/Service-Installation#deploying-the-ova) about setting up the OVA, which includes steps to configure networking.
