### ISSUE TITLE
CAS verify_only Job requires both source and target configuration

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ecs-sync#63]
Dear all
I wanted to create a verify_only Job for CAS data on an ECS system. This requires to create both a source CAS and a target CAS definition. With only one of them the UI tells me that it's missing a selection.
Any idea as to why a verify_only would required both source and target?

Further this job then reads the data twice. If source and target definition are identical the result should still be ok.
But what if someone has a different source and target: which verification result is then stored in the single status field? The one from source or from the target?

I would like to avoid generating twice the required load on the ECS and any idea to achieve this are welcomed.

Best regards, Holger

**Comment by twincitiesguy** [comment]
When you verify data, you are comparing the source with the target.  Each object on the source (or in the list file) is read and checksummed, then it is read and checksummed from the target.  The 2 checksums are compared and, if they match, the object is verified.

With the verify option, this is done after the data is copied.  Verify-only, will not try to copy data first, but simply read both sides and verify.

Are you simply trying to check if the objects in a list exist?  You can probably do that with another tool, like Centera Exerciser or JCASQuery.

**Comment by holgerjakob** [comment]
Thank you very much for the explanation. This helps already to understand the behaviour and we are absolutely happy with that. Tools like CE and JCASQuery will need more explanations towards the customer which is why we thought that having it on ECSSync is more intuitive.
