### ISSUE TITLE
Not finding OVA link to 3.3.1

### ISSUE THREAD

**Issue by goncav** [EMCECS/ecs-sync#70]
Hello, does anyone have the 3.3.1 OVA link?

thank you

**Comment by goncav** [comment]
> Hello, does anyone have the 3.3.1 OVA link?
> 
> thank you

found a link to 3.2.7 and I was informed to update ECSsync to 3.1.1 after deploy
https://github.com/EMCECS/ecs-sync/wiki/Software-Upgrade

**Comment by MarkHe1222** [comment]
Hi @goncav  , we haven't release the OVA of 3.3.1, but you can install the OVA 3.2.7, and then replace the jars of 3.3.1 in https://github.com/EMCECS/ecs-sync/releases  follow the https://github.com/EMCECS/ecs-sync/wiki/Software-Upgrade

**Comment by michaelpringle** [comment]
Why is there still no OVA for 3.3.1?   When can we expect one?

**Comment by twincitiesguy** [comment]
Instead of relying on the OVA, you can also use a canned OVA or ISO for CentOS 7, and then install ecs-sync on it: https://github.com/EMCECS/ecs-sync/wiki/Service-Installation.  There may not be another public release of the OVA.
