### ISSUE TITLE
CLI Jobname Specification possible?

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ecs-sync#84]
Dear all

Does the CLI provide the possibility to provide a jobname input?
In the CLI Documentation I was unable to find that parameter.

Thanks a lot, Holger

**Comment by spodiedog** [comment]
I understand the job name is the file name used to submit the job.  Since this name is specific to the submit invocation, it can only be given once and not changed.

**Comment by holgerjakob** [comment]
Thanks spdiedog. I will give it a try and check this out.
