### ISSUE TITLE
MariaDB ecssync default password

### ISSUE THREAD

**Issue by Antonin13** [EMCECS/ecs-sync#88]
Hi folks,

did the default password for ecssync user in MariaDB change since ECSsync v3.3 ? I am not able to log in 3.4.2 and 3.5.
Also I am not able to make the sync work as the dbtable can´t be created due to the issue with ecssync credetials.

[ecssync@ecs-sync-linux ecs-sync-3.5.0]$ mysql ecs_sync -u ecssync -p
Enter password:
ERROR 1045 (28000): Access denied for user 'ecssync'@'localhost' (using password: YES)

Thanks.

**Comment by xiaoxin-ren** [comment]
No, it isn't changed. 
Can you please try below DB configuration(copied from `sample/ecs-s3-bucket-copy.xml`) and see if sync is still working? 
```
<dbConnectString>jdbc:mysql://localhost:3306/ecs_sync?user=ecssync&amp;autoReconnect=true&amp;characterEncoding=UTF-8</dbConnectString>
<dbEncPassword>Z0TUQ+sciX2fp623Iu9LcQ==</dbEncPassword>
```

**Comment by Antonin13** [comment]
Yes, I have this in the xml
But I get this error anyway:

2022-01-31 20:29:02 ERROR [sync-pool-1-t-2] MySQLDbService: could not create DB table testclip8. note: name may only contain alphanumeric or underscore
2022-01-31 20:29:02 WARN  [sync-pool-1-t-2] SyncTask: error setting DB status
org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'ecssync'@'localhost' (using password: YES)

I also tried to change the encrypted database password according https://github.com/EMCECS/ecs-sync/wiki/Encrypted-Database-Passwords, but without success.

**Comment by xiaoxin-ren** [comment]
It sounds like MariaDB user ecssync isn't assigned with default password. An idea is to login MiraDB by root and modify ecssync password so that you are able to login, then generate Encrypted password from ` /opt/emc/ecs-sync/bin/ecs-sync-enc-passwd`  to use in sync task.

**Comment by dunedodo** [comment]
@Antonin13 As it has been a long time since the last response, I'll close the ticket. Please feel free to reopen it if you hit the same issue.
