### ISSUE TITLE
ECS Sync for S3 Buckets with object lock enabled and object locked objects

### ISSUE THREAD

**Issue by holgerjakob** [EMCECS/ecs-sync#90]
Dear all

As @twincitiesguy as suggested to post also enhancement requests, here is one that I would see use for. We are potentially migrating from another S3 on premise storage to ECS. There may already be buckts and objects that are under object lock retention which would have to be maintained with their retention periods.
It would be great if ECSSync could be used to migrate.

Take care, Holger

**Comment by xiaoxin-ren** [comment]
Thanks for raising the request. It will be planned and supported.

**Comment by holgerjakob** [comment]
Dear all

Any update on this?

We are nearly one year later now and start to see the usage of object lock on a regular basis.
With an F900 project at hand we have to start thinking about migration procedures should it not be rpq-able to extend a replication group to an AFA system.

Thanks a lot, Holger

**Comment by xiaoxin-ren** [comment]
@holgerjakob, we plan to publish this feature in the next release, however, we need more test and the release date isn't decided. It will be ideal if PS is involved for the migration, so that we can have a test build for PS to try and verify if the function fits your request.

**Comment by holgerjakob** [comment]
Hi @xiaoxin-ren 
It has now been confirmed. We need to migrate to EXF900 using ECSSync.
As ECS Service Enabled Partner, we do generally provide the PS Work ourselves. 
What do you need to make this functionality happen?

Best regards, Holger

**Comment by xiaoxin-ren** [comment]
@holgerjakob , the feature code is mostly ready. The design needs to cover compatibility with ECS legacy retention, that's why we need more tests. Please reach PS and ask for a test binary so that you can try and report any issue so that we can fix before release.

**Comment by xiaoxin-ren** [comment]
@holgerjakob, v3.5.3 is now released to support Object Lock migration. Please take a try. Please note that ecs-sync does not migrate bucket level configurations, it's for S3 objects.
