### ISSUE TITLE
Download SDK for CAS

### ISSUE THREAD

**Issue by Limouni-anas** [EMCECS/ecs-sync#91]
Hello Team
could you please share with us a link to download the SDK for the CAS at the step N°7 at the service installation Step for ECS-sync.
the link :https://developer-content.emc.com/downloads/centera/download.htm is not available.

thank you for your support.

BR

**Comment by holgerjakob** [comment]
Hi 

Try
https://www.dell.com/support/home/en-us/product-support/product/centera-sdk/drivers 

Best regards, Holger
