### ISSUE TITLE
ECSSYNC DD Cloud Unit Migration

### ISSUE THREAD

**Issue by mpmafra1403** [EMCECS/ecs-sync#97]
Hi Folks, someone has worked in DD Cloud Unit migration? We are replacing Storage Object (ICOS) to ECS and we need to move this legacy data without Data Lost, so are ther any way to clone access key and security key from source storage to target storage? I will use ECSSYNC to move data and need to know what is the best way to do it. thanks for your time.

**Comment by xiaoxin-ren** [comment]
ECS Sync will only migrate storage data, not account info. Would you contact PS team or account team and ask them to seek the best resolution for you?
